### ISSUE TITLE
Se debre almacenar la asignaturas de la forma más adecuada para las HUs

### ISSUE THREAD

**Issue by JJ** [Carlossamu7/CC1-Conservatorio#59]
https://github.com/Carlossamu7/CC1-Conservatorio/blob/9de2e18b79b71a538b1f22e15a3cfaaaee0ef72a/src/Alumno.py#L59
No parece haber ninguna historia de usuario que permita que se borren todas las asignaturas y se pongan otras nuevas. Sin comprobaciones, además.

Y en una cadena separada por comas no parece lo más correcto. Ni siquiera una lista de strings parece correcto. ¿No hay una clase Asignatura?

**Comment by Carlossamu7** [comment]
El método `setAsignaturas` ha sido eliminado en #58.

Efectivamente, no es lo más eficiente guardar las asignaturas como un único *string* separado por comas y espacios. Se ha valorado la opción de usar la clase `Asignatura` pero no parece lo más correcto porque dicha clase tiene el aula, horario, profesor y otros campos que no son de interés para el alumno. Es más, es posible que en el momento de la matriculación esto no se sepa (en la Universidad normalmente sí se sabe en el momento de la matriculación pero no es así en los Conservatorios) y la asignatura no esté dada de alta. Por eso me parece lo más correcto cambiar a usar una lista de *strings* lo cual elimina el método `lista_asignaturas` y simplifica y hace más eficiente algunas cosas.

Muy buena aportación. ¡Muchas gracias!
